export const projects = [
  {
    name: "Study Notion",
    description: [
      "🎓📚 Created a responsive Ed-Tech platform using React.js, TailwindCSS, and Express.js, enabling users to seamlessly create, consume, and rate educational content.",
      "💳 Integrated Razorpay for secure payments, facilitating course enrollment and instructor earnings, and implemented JWT for secure user authentication and authorization 🔐.",
      "📊 Established a robust RESTful API communication system between front-end and back-end components, utilizing Mongoose with Express.js for efficient CRUD operations on the MongoDB database.",
      "🌐📁 Leveraged Cloudinary for seamless file uploads, guaranteeing improved scalability, customization, and superior media management. The frontend is hosted on Vercel, while the backend resides on Render 🚀",
    ],
    skills: [
      "React.js",
      "Tailwind CSS",
      "Express.js",
      "JWT",
      "Razorpay",
      "RESTfulAPI",
      "Mongoose",
      "MongoDB",
      "Cloudinary",
      "Vercel",
      "Render",
    ],
    livelink: "",
    githublink: "",
  },
  {
    name: "Study Notion",
    description: [
      "Created a responsive Ed-Tech platform using React.js, TailwindCSS, and Express.js, enabling users to seamlessly create,consume, and rate educational content",
      "Integrated Razorpay for secure payments, facilitating course enrollment and instructor earnings, and implemented JWT forsecure user authentication and authorization",
      "Established a robust RESTful API communication system between front-end and back-end components, utilizing Mongoosewith Express.js for efficient CRUD operations on the MongoDB database.",
      "Leveraged Cloudinary for seamless file uploads, guaranteeing improved scalability, customization, and superior mediamanagement. The frontend is hosted on Vercel, while the backend resides on Render.",
    ],
    skills: [
      "React.js",
      "Tailwind CSS",
      "Express.js",
      "JWT",
      "Razorpay",
      "RESTfulAPI",
      "Mongoose",
      "MongoDB",
      "Cloudinary",
      "Vercel",
      "Render",
    ],
    livelink: "",
    githublink: "",
  },
  {
    name: "Study Notion",
    description: [
      "Created a responsive Ed-Tech platform using React.js, TailwindCSS, and Express.js, enabling users to seamlessly create,consume, and rate educational content",
      "Integrated Razorpay for secure payments, facilitating course enrollment and instructor earnings, and implemented JWT forsecure user authentication and authorization",
      "Established a robust RESTful API communication system between front-end and back-end components, utilizing Mongoosewith Express.js for efficient CRUD operations on the MongoDB database.",
      "Leveraged Cloudinary for seamless file uploads, guaranteeing improved scalability, customization, and superior mediamanagement. The frontend is hosted on Vercel, while the backend resides on Render.",
    ],
    skills: [
      "React.js",
      "Tailwind CSS",
      "Express.js",
      "JWT",
      "Razorpay",
      "RESTfulAPI",
      "Mongoose",
      "MongoDB",
      "Cloudinary",
      "Vercel",
      "Render",
    ],
    livelink: "",
    githublink: "",
  },
  {
    name: "Study Notion",
    description: [
      "Created a responsive Ed-Tech platform using React.js, TailwindCSS, and Express.js, enabling users to seamlessly create,consume, and rate educational content",
      "Integrated Razorpay for secure payments, facilitating course enrollment and instructor earnings, and implemented JWT forsecure user authentication and authorization",
      "Established a robust RESTful API communication system between front-end and back-end components, utilizing Mongoosewith Express.js for efficient CRUD operations on the MongoDB database.",
      "Leveraged Cloudinary for seamless file uploads, guaranteeing improved scalability, customization, and superior mediamanagement. The frontend is hosted on Vercel, while the backend resides on Render.",
    ],
    skills: [
      "React.js",
      "Tailwind CSS",
      "Express.js",
      "JWT",
      "Razorpay",
      "RESTfulAPI",
      "Mongoose",
      "MongoDB",
      "Cloudinary",
      "Vercel",
      "Render",
    ],
    livelink: "",
    githublink: "",
  },
];
